# Branch-Pruner-Easy | GitHub Action Workflow
# 
# Description: Truncates the old commit history of the current main branch with minimal settings
# Author: Sitdisch
# Source: https://github.com/myactionway/branch-pruner-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch
# 
# CAUTION: IT IS A POWERFUL TOOL AND YOU USE IT AT YOUR OWN RISK. CUTS CAN'T BE UNDONE.

name: 'Branch-Pruner-Easy'

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as environmental variables (env) for not manually triggered workflows 
env:
  NEW_FIRST_COMMIT: HEAD~30 # e.g. commit-hash or HEAD~N etc.
  TOKEN_NAME: BRANCH_PRUNER # target token name; insert only the name never the real value e.g. 'BRANCH_PRUNER_TOKEN'
  # 
  # THAT'S IT; JUMP TO THE TRIGGERS;
  DEFAULT_REPOSITORY: ${{ github.repository }} # repo with this file
  DEFAULT_BRANCH: 'main'

# TRIGGERS
on:
  # push:
  # schedule: # Check your schedule here => https://crontab.guru/
  #   - cron: '00 23 28 * *' # e.g. every 28th day of a month at 23:00
  # 
  # THAT'S IT; YOU'RE DONE;
  workflow_dispatch:
    inputs:
      new_first_commit:
        description: 'New first commit'
        required: true
      token_name:
        description: 'Target token name (NO VALUE!)'
        required: true

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  branch-pruner-easy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.DEFAULT_REPOSITORY }}
          token: ${{ secrets[github.event.inputs.token_name] || secrets[env.TOKEN_NAME] }}
          fetch-depth: '0'
          ref: ${{ env.DEFAULT_BRANCH }}
      - uses: myactionway/branch-pruner-action@v2.0
        with:
          new_first_commit: ${{ github.event.inputs.new_first_commit || env.NEW_FIRST_COMMIT }}
          branch: ${{ env.DEFAULT_BRANCH }}
