name: F-Droid Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  Fdroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete Extra stuff
        run: |
          echo "The only reason this exists is bc gh pages is getting slow due to the size of some files, this removes as much as possible keeping the actual page lightweight so it deploys faster"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b droid
          for filename in ./metadata/*.yml; do     rm -rf repo/"$(echo $filename | sed 's/.\/metadata\///' | sed 's/\.yml//')"/en-US/icon.png;     rm -rf repo/"$(echo $filename | sed 's/.\/metadata\///' | sed 's/\.yml//')"/en-US/featureGraphic.png; done
          rm -rf "repo/index.css" "repo/index.html" "repo/index.jar" "repo/index.xml"
          rm -rf "metadata" "APPS.md" "README.md" ".gitignore" ".github/"
          git add --all
          git commit -m "Push F-Droid repo"
          git push origin droid --force
