name: GitLab Mirror

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["F-Droid Deploy"]
  push:
    branches: [ droid ]

jobs:
  GitLab:
    runs-on: ubuntu-latest
    steps:
      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CRED}}

      - name: Push to GitLab
        run: |
          echo "This Exists as a backup to make ensure connectivity"
          git clone -b droid https://github.com/WmeLuna/fdroid.git && cd fdroid > /dev/null
          git lfs fetch --all
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://gitlab.com/WmeLuna/fdroid.git
          git branch -M main
          git push -uf origin main
